set nocompatible " Vim goodness plz
set noswapfile   " Anoooooooying

set title        " Set terminal title when vim is open
set enc=utf-8    " Always make UTF-8 files

" Pathogen is a Vim plugin that makes it easy to install other Vim plugins
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

filetype plugin indent on
syntax on


"---------------------------------------------------------
" Default Options, some overriden later based on filetypes
"---------------------------------------------------------

" Set hard wrap for lines and no text wrapping.
set textwidth=79
set nowrap

" Indentation options
set smarttab
set expandtab
set smartindent
set autoindent
set tabstop=2
set shiftwidth=2

" Customize tab completion for filenames
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,.svn,.hg

" Turn on line numbers and row/column numbers
set nu
set ruler
set showcmd

if has("statusline")
  set statusline=%<%f\ %h%m%r%=%{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}%k\ %-14.(%l,%c%V%)\ %P
  set laststatus=2
endif

" Fix backspace key
set bs=2

" Set searching
set incsearch
set ignorecase
set smartcase

if has('autocmd')
  " Whitespace Gestapo; finds stray spaces at end of lines
  " Dont do this if the filetype indicates Conque is running!
  highlight ExtraWhitespace ctermbg=red guibg=red
  autocmd BufWinEnter *\
        \ if &ft != 'conque_term' |
        \   match ExtraWhitespace /\s\+$/ |
        \ endif
  autocmd InsertEnter *
        \ if &ft != 'conque_term' |
        \   match ExtraWhitespace /\s\+\%#\@<!$/ |
        \ endif
  autocmd InsertLeave *
        \ if &ft != 'conque_term' |
        \   match ExtraWhitespace /\s\+$/ |
        \ endif
  autocmd BufWinLeave * call clearmatches()
endif

let vimrplugin_underscore=0

"---------------------------------------------------------
" Filetype-Specific Options
"---------------------------------------------------------
" Fortran
let fortran_free_source=1

" R
" Yes. Underscore was used for assignment ages ago and this would be helpful
" for replacing it with '<-'. If it was still 1990.  Now it is the single most
" annoying default I have ever seen.
let vimrplugin_underscore=0

if has("autocmd")
  " HTML
  " no hard wraps cause URLS are quite long and nesting is usually quite deep
  " which leads to inconvienant line wrapping which leads to strong languange
  " and strong drink
  autocmd FileType html setlocal textwidth=0


  " Makefiles
  autocmd FileType make setlocal noexpandtab


  " Markdown files
  autocmd BufRead,BufNewFile {*.md,*.mdown,*.markdown,*.ronn} set filetype=markdown


  " Python
  " smartindent screws with comment indentation for some reason
  autocmd FileType python setlocal shiftwidth=4 tabstop=4 colorcolumn=80 nosmartindent
  autocmd BufRead,BufNewFile *.pyd set filetype=pyrex


  " SCSS syntax highlighting.
  autocmd BufRead,BufNewFile *.scss set filetype=scss


  " Misc. ruby files
  autocmd BufRead,BufNewFile {Rakefile,Vagrantfile} set filetype=ruby


  " TikZ files are LaTeX files
  autocmd BufRead,BufNewFile *.tikz set filetype=tex


  " Wiki Files
  autocmd BufRead,BufNewFile *.wiki set filetype=wiki

endif

