set nocompatible " Vim goodness plz
set noswapfile   " Anoooooooying

set title        " Set terminal title when vim is open
set enc=utf-8    " Always make UTF-8 files

" Pathogen is a Vim plugin that makes it easy to install other Vim plugins
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

filetype plugin indent on
syntax on


"---------------------------------------------------------
" Default Options, some overriden later based on filetypes
"---------------------------------------------------------

" Set hard wrap for lines and no text wrapping.
set textwidth=79
set nowrap

" Indentation options
set smarttab
set expandtab
set smartindent
set autoindent
set tabstop=2
set shiftwidth=2

" Turn on line numbers and row/column numbers
set nu
set ruler
set showcmd

if has("statusline")
  set statusline=%<%f\ %h%m%r%=%{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}%k\ %-14.(%l,%c%V%)\ %P
  set laststatus=2
endif

" Fix backspace key
set bs=2

" Set searching
set incsearch
set ignorecase
set smartcase

if has('autocmd')
  " Whitespace Gestapo; finds stray spaces at end of lines
  " Dont do this if the filetype indicates Conque is running!
  highlight ExtraWhitespace ctermbg=red guibg=red
  autocmd BufWinEnter *\
        \ if &ft != 'conque_term' |
        \   match ExtraWhitespace /\s\+$/ |
        \ endif
  autocmd InsertEnter *
        \ if &ft != 'conque_term' |
        \   match ExtraWhitespace /\s\+\%#\@<!$/ |
        \ endif
  autocmd InsertLeave *
        \ if &ft != 'conque_term' |
        \   match ExtraWhitespace /\s\+$/ |
        \ endif
  autocmd BufWinLeave * call clearmatches()
endif


"---------------------------------------------------------
" Filetype-Specific Options
"---------------------------------------------------------
" Fortran
let fortran_free_source=1

if has("autocmd")
  " HTML
  autocmd FileType html setlocal textwidth=0

  " Python
  autocmd FileType python setlocal shiftwidth=4 tabstop=4 colorcolumn=79

  " SCSS syntax highlighting.
  autocmd BufRead,BufNewFile *.scss set filetype=scss

  " Vagrantfiles are ruby files
  autocmd BufRead,BufNewFile Vagrantfile set filetype=ruby
endif

